CREATE TABLE document_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id VARCHAR(128) NOT NULL,
    state_update BYTEA NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_document_updates_document_id_id ON document_updates (document_id, id);
