spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/rtcodeeditor}
spring.datasource.username=${DATABASE_USERNAME:rtcodeeditor}
spring.datasource.password=${DATABASE_PASSWORD:rtcodeeditor}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
server.port=${PORT:8095}
